import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';
import assert from 'node:assert/strict';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const keys=['touchline.career.v1','touchline.history.v1','touchline.lifetime.v1','touchline.seen.v1'];
function store(seed={},fail=false){const m=new Map(Object.entries(seed));return {getItem:k=>m.get(k)??null,setItem(k,v){if(fail)throw Error('denied');m.set(k,String(v));},removeItem:k=>m.delete(k),m};}
function load(localStorage,sessionStorage){const source=html.match(/<script id="guest-storage">([\s\S]*?)<\/script>/)?.[1];assert.ok(source,'guest-storage module exists');const c=vm.createContext({localStorage,sessionStorage});vm.runInContext(source+';globalThis.storage=GuestStorage',c);return c.storage;}
test('legacy gameplay migrates verbatim, settings stay local, refresh retains session',()=>{const legacy=Object.fromEntries(keys.map((k,i)=>[k,JSON.stringify({engaged:i,hints:1})]));const local=store({...legacy,'touchline.language.v1':'en','derabona.analytics-consent.v1':'declined'}),session=store();let s=load(local,session);for(const k of keys){assert.equal(s.getItem(k),legacy[k]);assert.equal(local.getItem(k),null);}assert.equal(local.getItem('touchline.language.v1'),'en');assert.equal(local.getItem('derabona.analytics-consent.v1'),'declined');s=load(local,session);assert.equal(s.getItem(keys[0]),legacy[keys[0]]);assert.equal(load(local,store()).getItem(keys[0]),null);});
test('failed migration retains ALL originals and supplies memory gameplay',()=>{const local=store(Object.fromEntries(keys.map(k=>[k,'legacy']))),session=store({},true),s=load(local,session);for(const k of keys)assert.equal(local.getItem(k),'legacy');assert.equal(s.persistent,false);s.setItem(keys[0],'new');assert.equal(s.getItem(keys[0]),'new');});
test('readback mismatch never removes legacy originals',()=>{const local=store({[keys[0]]:'original'}),session=store();session.setItem=()=>{};load(local,session);assert.equal(local.getItem(keys[0]),'original');});
test('conflicting session preserves the entire legacy snapshot without mixing keys',()=>{const legacy=Object.fromEntries(keys.map((k,i)=>[k,i?'legacy-'+i:'LEGACY']));const local=store(legacy),session=store({[keys[0]]:'OTHER_SESSION_SAVE'}),s=load(local,session);for(const k of keys)assert.equal(local.getItem(k),legacy[k]);assert.equal(s.getItem(keys[0]),'OTHER_SESSION_SAVE');for(const k of keys.slice(1))assert.equal(s.getItem(k),null);assert.equal(s.legacyConflict,true);});
test('partial matching session is not merged with a different legacy snapshot',()=>{const local=store({[keys[0]]:'same',[keys[1]]:'old history'}),session=store({[keys[0]]:'same'}),s=load(local,session);assert.equal(local.getItem(keys[1]),'old history');assert.equal(s.getItem(keys[1]),null);});
test('explicit recovery replaces linked snapshot and verifies before deleting originals',()=>{const legacy=Object.fromEntries(keys.map(k=>[k,'legacy'])),local=store(legacy),session=store({[keys[0]]:'other'}),s=load(local,session);assert.equal(s.restoreLegacy(),true);for(const k of keys){assert.equal(session.getItem(k),'legacy');assert.equal(local.getItem(k),null);}assert.equal(s.legacyConflict,false);});
test('failed explicit recovery preserves all legacy originals',()=>{const local=store(Object.fromEntries(keys.map(k=>[k,'legacy']))),session=store({[keys[0]]:'other'},true),s=load(local,session);assert.equal(s.restoreLegacy(),false);for(const k of keys)assert.equal(local.getItem(k),'legacy');});
test('reset affects gameplay only and memory fallback works',()=>{const local=store({'touchline.language.v1':'es'}),s=load(local,store({},true));s.setItem(keys[0],'current');s.clear();assert.equal(s.getItem(keys[0]),null);assert.equal(local.getItem('touchline.language.v1'),'es');});
test('OAuth callback scrub precedes analytics and preserves only language',()=>{const source=html.match(/<script id="auth-callback">([\s\S]*?)<\/script>/)?.[1];assert.ok(source,'auth callback module exists');let replaced;const c=vm.createContext({URL,URLSearchParams,location:{href:'https://derabona.club/?lang=en&code=secret&state=secret#access_token=secret&refresh_token=private'},history:{replaceState:(_,__,v)=>replaced=String(v)}});vm.runInContext(source+';globalThis.callback=AuthCallback',c);assert.equal(replaced,'https://derabona.club/?lang=en');assert.ok(html.indexOf('id="auth-callback"')<html.indexOf('id="analytics"'));assert.equal(c.callback.code,'secret');});
