// Real Chromium, explicitly mocked SDK/API. Not hosted OAuth/database evidence.
async page => {
 const context=await page.context().browser().newContext({viewport:{width:375,height:667}}),checks=[],calls=[],errors=[];
 const ok=(v,s)=>{if(!v)throw Error(s);checks.push(s);};
 let fail=false,hold=false,release,own=true,expired=false,shortNames=false;
 try{
 await context.addInitScript(()=>{window.mockSession=null;window.authListener=null;});
 await context.route('https://cdn.jsdelivr.net/npm/@supabase/**',r=>r.fulfill({contentType:'application/javascript',body:`window.supabase={createClient:(u,k,c)=>{window.authConfig=c;return {auth:{getSession:async()=>({data:{session:window.mockSession},error:null}),onAuthStateChange:fn=>{window.authListener=fn;return {data:{subscription:{unsubscribe(){}}}};}}};}};`}));
 await context.route('**/functions/v1/ranked-game',async r=>{if(r.request().method()==='OPTIONS')return r.fulfill({status:204,headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*'}});const body=r.request().postDataJSON();calls.push({body,headers:r.request().headers()});const capturedOwn=own;if(hold){hold=false;await new Promise(resolve=>release=resolve);}const headers={'access-control-allow-origin':'*'};if(expired&&r.request().headers().authorization)return r.fulfill({status:401,headers,body:'{}'});if(fail){fail=false;return r.fulfill({status:500,headers,body:'{}'});}const total=body.competition==='brasileirao'?0:23;return r.fulfill({contentType:'application/json',headers,body:JSON.stringify({competition:body.competition,total,entries:Array.from({length:Math.min(20,Math.max(0,total-body.offset))},(_,j)=>({rank:body.offset+j<2?1:body.offset+j+1,nickname:shortNames?['Luna','Mateo','Nico'][j%3]:j===0?'<img src=x onerror=alert(1)>':'LongNicknameWithoutSpaces24',points:j<2?500:400-j,answered:7,correct:5})),own:r.request().headers().authorization&&capturedOwn?{rank:42,points:73}:null})});});
 const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:4173/leaderboard.html?competition=bad&lang=en&code=SECRET&state=SECRET#access_token=SECRET');
 await p.locator('#leaderboard-table').waitFor({state:'visible'});
 ok(await p.locator('h1').textContent()==='Leaderboard','Standalone English page');
 ok(!p.url().includes('SECRET')&&p.url().includes('competition=all'),'URL normalized and OAuth secrets discarded');
 ok(await p.locator('nav [aria-current="page"]').textContent()==='Leaderboard','Active semantic navigation');
 ok(await p.locator('#leaderboard-entries tr').count()===20&&!await p.locator('#leaderboard-entries img').count(),'Twenty safe text rows');
 ok(!calls.at(-1).headers.authorization,'Guest board anonymous');
 ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Short mobile has no horizontal overflow');
 await p.locator('#board-next').click();await p.waitForFunction(()=>document.querySelectorAll('#leaderboard-entries tr').length===3);ok(calls.at(-1).body.offset===20,'Real next offset');
 await p.locator('#leaderboard-filter').selectOption('brasileirao');await p.waitForFunction(()=>document.querySelector('#leaderboard-status').dataset.state==='empty');ok(calls.at(-1).body.offset===0&&await p.locator('#board-next').isHidden(),'Empty filter resets pagination');
 fail=true;await p.locator('#leaderboard-filter').selectOption('la-liga');await p.locator('#board-retry').waitFor({state:'visible'});await p.locator('#board-retry').click();await p.locator('#leaderboard-table').waitFor({state:'visible'});ok(calls.at(-1).body.competition==='la-liga','Error retry retains competition');
 await p.goBack();await p.waitForFunction(()=>document.querySelector('#leaderboard-filter').value==='brasileirao');await p.goForward();await p.locator('#leaderboard-table').waitFor({state:'visible'});ok(await p.locator('#leaderboard-filter').inputValue()==='la-liga','Back and forward restore filter');
 await p.locator('#language').selectOption('es');ok(await p.locator('h1').textContent()==='Clasificación'&&await p.locator('#play-link').textContent()==='Jugar','Spanish UI and navigation');
 await p.evaluate(()=>{window.mockSession={access_token:'TEST_TOKEN',user:{id:'user-a'}};localStorage.setItem('derabona.auth.v1','MOCK');window.dispatchEvent(new StorageEvent('storage',{key:'derabona.auth.v1'}));});
 await p.waitForFunction(()=>document.querySelector('#leaderboard-own').textContent.includes('42'));ok((await p.locator('#leaderboard-own').textContent()).includes('73'),'Own off-page rank and points');
 fail=true;await p.locator('#leaderboard-filter').selectOption('premier-league');await p.locator('#board-retry').waitFor({state:'visible'});ok((await p.locator('#personal-detail').textContent()).includes('No pudimos cargar tu posición'),'Signed-in error does not claim no rank');await p.locator('#board-retry').click();await p.waitForFunction(()=>document.querySelector('#leaderboard-own').textContent.includes('42'));ok(true,'Signed-in error retry restores own rank');
 await context.setOffline(true);await p.evaluate(()=>window.dispatchEvent(new Event('offline')));ok((await p.locator('#personal-detail').textContent()).includes('No pudimos cargar tu posición')&&await p.locator('#leaderboard-own').textContent()==='','Signed-in offline clears rank without claiming no result');await context.setOffline(false);await p.locator('#board-retry').click();await p.waitForFunction(()=>document.querySelector('#leaderboard-own').textContent.includes('42'));ok(true,'Online retry restores own rank');
 hold=true;await p.locator('#leaderboard-filter').selectOption('all');while(!release)await p.waitForTimeout(10);own=false;await p.evaluate(()=>{window.mockSession={access_token:'OTHER',user:{id:'user-b'}};window.authListener('SIGNED_IN',window.mockSession);});ok(!(await p.locator('#leaderboard-own').textContent()).includes('42'),'Account switch clears own synchronously');release();release=null;await p.locator('#leaderboard-table').waitFor({state:'visible'});ok(!(await p.locator('#leaderboard-own').textContent()).includes('42'),'Late old identity response rejected');
 ok((await p.locator('#personal-detail').textContent()).includes('Todavía no tenés un puesto'),'Successful authenticated own null shows no-result copy');
 own=true;await p.locator('#leaderboard-filter').selectOption('la-liga');await p.waitForFunction(()=>document.querySelector('#leaderboard-own').textContent.includes('42'));
 const beforeExpired=calls.length;expired=true;await p.locator('#leaderboard-filter').selectOption('premier-league');await p.locator('#leaderboard-table').waitFor({state:'visible'});ok(calls.length===beforeExpired+2&&!!calls[beforeExpired].headers.authorization&&!calls.at(-1).headers.authorization&&await p.locator('#leaderboard-own').textContent()==='','Expired bearer retries once anonymously and clears own');expired=false;
 await p.locator('#leaderboard-filter').selectOption('all');await p.waitForFunction(()=>document.querySelector('#leaderboard-own').textContent.includes('42'));await p.evaluate(()=>{window.mockSession=null;localStorage.removeItem('derabona.auth.v1');window.authListener('SIGNED_OUT',null);});ok(await p.locator('#leaderboard-own').textContent()==='','Signout clears own synchronously');await p.locator('#leaderboard-table').waitFor({state:'visible'});ok(!calls.at(-1).headers.authorization,'Signout reload is anonymous');
 shortNames=true;await p.locator('#leaderboard-filter').selectOption('la-liga');await p.locator('#leaderboard-table').waitFor({state:'visible'});await p.evaluate(()=>scrollTo(0,0));const mobileY=await p.locator('#leaderboard-entries tr').first().evaluate(e=>e.getBoundingClientRect().top);ok(mobileY<600,'Mobile first row below 600px: '+mobileY);ok(await p.locator('#answered-label').evaluate(e=>parseFloat(getComputedStyle(e).fontSize)>=12),'Mobile headers at least 12px');
 await p.setViewportSize({width:1440,height:900});await p.evaluate(()=>scrollTo(0,0));const desktopRows=await p.locator('#leaderboard-entries tr').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().bottom<=innerHeight).length);ok(desktopRows>=5,'Desktop shows several complete rows: '+desktopRows);await p.setViewportSize({width:375,height:667});
 ok(await p.locator('#account-link').textContent()==='Iniciar sesión','Clear sign-in CTA');await p.locator('#account-link').click();await p.locator('#account-dialog').waitFor({state:'visible'});ok(await p.locator('#account-dialog').evaluate(e=>e.open),'Account CTA opens real dialog');await p.goto('http://127.0.0.1:4173/leaderboard.html?lang=en');await p.locator('#leaderboard-table').waitFor({state:'visible'});
 ok(calls.every(c=>c.body.action==='leaderboard'&&c.body.limit===20),'Only read-only leaderboard requests');
 await context.clearCookies();await p.evaluate(()=>localStorage.clear());await context.route('https://cdn.jsdelivr.net/npm/@supabase/**',r=>r.abort());await p.evaluate(()=>localStorage.setItem('derabona.auth.v1','MOCK'));await p.reload();await p.locator('#leaderboard-table').waitFor({state:'visible'});ok(!calls.at(-1).headers.authorization,'Failed SDK leaves public board usable');
 await p.evaluate(()=>localStorage.clear());await p.goto('http://127.0.0.1:4173/index.html?lang=en');await p.locator('#hint').click();const saved=await p.evaluate(()=>sessionStorage.getItem('touchline.career.v1'));await p.locator('#leaderboard-open').click();await p.locator('#leaderboard-table').waitFor({state:'visible'});ok(await p.evaluate(v=>sessionStorage.getItem('touchline.career.v1')===v,saved),'Board does not mutate gameplay save');await p.locator('#play-link').click();await p.locator('#hint').waitFor();ok(await p.evaluate(v=>sessionStorage.getItem('touchline.career.v1')===v,saved),'Game-board-game preserves engaged round');
 ok(errors.length===0,'No runtime errors');return {passed:true,backend:'EXPLICIT SDK/API ROUTE MOCKS',checks,errors};
 }catch(error){throw Error(error.message+' errors: '+errors.join(',')+' calls: '+JSON.stringify(calls.slice(-3))+' | passed: '+checks.join('; '));}finally{release?.();await context.close();}
}
