// Real Chromium, explicitly mocked SDK/API. Not hosted OAuth/database evidence.
async page => {
 const context=await page.context().browser().newContext({viewport:{width:375,height:667}}),checks=[],calls=[],errors=[];
 const ok=(v,s)=>{if(!v)throw Error(s);checks.push(s);};
 let fail=false,hold=true,release,own=true,expired=false,shortNames=false;
 const loading=async(p,label)=>{await p.locator('#board-loading').waitFor({state:'visible',timeout:1500});ok(await p.locator('#board-results').getAttribute('aria-busy')==='true'&&await p.locator('#leaderboard-table').isHidden(),label+' shows prominent busy placeholder');};
 const settled=async(p,label)=>ok(await p.locator('#board-loading').isHidden()&&await p.locator('#board-results').getAttribute('aria-busy')==='false',label+' removes placeholder and busy state');
 // The native <select> filter was replaced by the same icon-list picker
 // dialog pattern as the main game's competition badge (see index.html);
 // drive it the same way a real click would, and read the selection back
 // from the URL's own competition= param (always kept in sync by
 // normalize()) rather than a <select>'s .value/.inputValue().
 const selectCompetition=async(p,id)=>{await p.locator('#change-board-competition').click();await p.locator('#board-competitions').waitFor({state:'visible'});await p.locator(`#board-competition-options .option[data-competition-id="${id}"]`).click();await p.locator('#board-competitions').waitFor({state:'hidden'});};
 const boardCompetition=p=>new URL(p.url()).searchParams.get('competition');
 try{
 await context.addInitScript(()=>{window.mockSession=null;window.authListener=null;});
 await context.route('https://cdn.jsdelivr.net/npm/@supabase/**',r=>r.fulfill({contentType:'application/javascript',body:`window.supabase={createClient:(u,k,c)=>{window.authConfig=c;return {auth:{getSession:async()=>({data:{session:window.mockSession},error:null}),onAuthStateChange:fn=>{window.authListener=fn;return {data:{subscription:{unsubscribe(){}}}};}}};}};`}));
 await context.route('**/functions/v1/ranked-game',async r=>{if(r.request().method()==='OPTIONS')return r.fulfill({status:204,headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*'}});const body=r.request().postDataJSON();calls.push({body,headers:r.request().headers()});const capturedOwn=own;if(hold){hold=false;await new Promise(resolve=>release=resolve);}const headers={'access-control-allow-origin':'*'};if(expired&&r.request().headers().authorization)return r.fulfill({status:401,headers,body:'{}'});if(fail){fail=false;return r.fulfill({status:500,headers,body:'{}'});}const total=body.competition==='brasileirao'?0:23;return r.fulfill({contentType:'application/json',headers,body:JSON.stringify({competition:body.competition,total,entries:Array.from({length:Math.min(20,Math.max(0,total-body.offset))},(_,j)=>({rank:body.offset+j<2?1:body.offset+j+1,nickname:shortNames?['Luna','Mateo','Nico'][j%3]:j===0?'<img src=x onerror=alert(1)>':'LongNicknameWithoutSpaces24',points:j<2?500:400-j,answered:7,correct:5})),own:r.request().headers().authorization&&capturedOwn?{rank:42,points:73}:null})});});
 const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:4173/leaderboard.html?competition=bad&lang=en&code=SECRET&state=SECRET#access_token=SECRET');
 await loading(p,'Deferred initial API');ok(await p.locator('#board-loading-label').textContent()==='Loading leaderboard…'&&await p.locator('#leaderboard-status').getAttribute('role')==='status','English loading has accessible live status');await p.locator('#language').selectOption('es');ok(await p.locator('#board-loading-label').textContent()==='Cargando clasificación…','Loading switches to Spanish without another request');await p.locator('#language').selectOption('en');while(!release)await p.waitForTimeout(10);release();release=null;
 await p.locator('#leaderboard-table').waitFor({state:'visible'});await settled(p,'Ready');
 ok(await p.locator('h1').textContent()==='Leaderboard','Standalone English page');
 ok(!p.url().includes('SECRET')&&p.url().includes('competition=all'),'URL normalized and OAuth secrets discarded');
 ok((await p.locator('#bottom-play').textContent()).trim().startsWith('Back'),'Single contextual nav action back to the game');
 ok(await p.locator('#leaderboard-entries tr').count()===20&&!await p.locator('#leaderboard-entries img').count(),'Twenty safe text rows');
 ok(!calls.at(-1).headers.authorization,'Guest board anonymous');
 ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Short mobile has no horizontal overflow');
 hold=true;await p.locator('#board-next').click();await loading(p,'Deferred next page');while(!release)await p.waitForTimeout(10);release();release=null;await p.waitForFunction(()=>document.querySelectorAll('#leaderboard-entries tr').length===3);ok(calls.at(-1).body.offset===20,'Real next offset');await settled(p,'Next ready');
 hold=true;await selectCompetition(p,'brasileirao');await loading(p,'Deferred filter');while(!release)await p.waitForTimeout(10);release();release=null;await p.waitForFunction(()=>document.querySelector('#leaderboard-status').dataset.state==='empty');ok(calls.at(-1).body.offset===0&&await p.locator('#board-next').isHidden(),'Empty filter resets pagination');await settled(p,'Empty');
 fail=true;await selectCompetition(p,'la-liga');await p.locator('#board-retry').waitFor({state:'visible'});await settled(p,'Error');await p.locator('#board-retry').click();await p.locator('#leaderboard-table').waitFor({state:'visible'});ok(calls.at(-1).body.competition==='la-liga','Error retry retains competition');
 await p.goBack();await p.waitForFunction(()=>new URL(location.href).searchParams.get('competition')==='brasileirao');await p.goForward();await p.locator('#leaderboard-table').waitFor({state:'visible'});ok(boardCompetition(p)==='la-liga','Back and forward restore filter');
 await p.locator('#language').selectOption('es');ok(await p.locator('h1').textContent()==='Clasificación'&&await p.locator('#account-link-label').textContent()==='Iniciar sesión','Spanish UI and navigation');
 await p.evaluate(()=>{window.mockSession={access_token:'TEST_TOKEN',user:{id:'user-a'}};localStorage.setItem('derabona.auth.v1','MOCK');window.dispatchEvent(new StorageEvent('storage',{key:'derabona.auth.v1'}));});
 await p.waitForFunction(()=>document.querySelector('#leaderboard-own').textContent.includes('42'));ok((await p.locator('#leaderboard-own').textContent()).includes('73'),'Own off-page rank and points');
 fail=true;await selectCompetition(p,'premier-league');await p.locator('#board-retry').waitFor({state:'visible'});ok((await p.locator('#personal-detail').textContent()).includes('No pudimos cargar tu posición'),'Signed-in error does not claim no rank');await p.locator('#board-retry').click();await p.waitForFunction(()=>document.querySelector('#leaderboard-own').textContent.includes('42'));ok(true,'Signed-in error retry restores own rank');
 await context.setOffline(true);await p.evaluate(()=>window.dispatchEvent(new Event('offline')));await settled(p,'Offline');ok((await p.locator('#personal-detail').textContent()).includes('No pudimos cargar tu posición')&&await p.locator('#leaderboard-own').textContent()==='','Signed-in offline clears rank without claiming no result');await context.setOffline(false);await p.locator('#board-retry').click();await p.waitForFunction(()=>document.querySelector('#leaderboard-own').textContent.includes('42'));ok(true,'Online retry restores own rank');
 hold=true;await selectCompetition(p,'all');while(!release)await p.waitForTimeout(10);own=false;await p.evaluate(()=>{window.mockSession={access_token:'OTHER',user:{id:'user-b'}};window.authListener('SIGNED_IN',window.mockSession);});ok(!(await p.locator('#leaderboard-own').textContent()).includes('42'),'Account switch clears own synchronously');release();release=null;await p.locator('#leaderboard-table').waitFor({state:'visible'});ok(!(await p.locator('#leaderboard-own').textContent()).includes('42'),'Late old identity response rejected');
 ok((await p.locator('#personal-detail').textContent()).includes('Todavía no tenés un puesto'),'Successful authenticated own null shows no-result copy');
 own=true;await selectCompetition(p,'la-liga');await p.waitForFunction(()=>document.querySelector('#leaderboard-own').textContent.includes('42'));
 const beforeExpired=calls.length;expired=true;await selectCompetition(p,'premier-league');await p.locator('#leaderboard-table').waitFor({state:'visible'});ok(calls.length===beforeExpired+2&&!!calls[beforeExpired].headers.authorization&&!calls.at(-1).headers.authorization&&await p.locator('#leaderboard-own').textContent()==='','Expired bearer retries once anonymously and clears own');expired=false;
 await selectCompetition(p,'all');await p.waitForFunction(()=>document.querySelector('#leaderboard-own').textContent.includes('42'));await p.evaluate(()=>{window.mockSession=null;localStorage.removeItem('derabona.auth.v1');window.authListener('SIGNED_OUT',null);});ok(await p.locator('#leaderboard-own').textContent()==='','Signout clears own synchronously');await p.locator('#leaderboard-table').waitFor({state:'visible'});ok(!calls.at(-1).headers.authorization,'Signout reload is anonymous');
 shortNames=true;await selectCompetition(p,'la-liga');await p.locator('#leaderboard-table').waitFor({state:'visible'});await p.evaluate(()=>scrollTo(0,0));const mobileY=await p.locator('#leaderboard-entries tr').first().evaluate(e=>e.getBoundingClientRect().top);ok(mobileY<600,'Mobile first row below 600px: '+mobileY);ok(await p.locator('#answered-label').evaluate(e=>parseFloat(getComputedStyle(e).fontSize)>=12),'Mobile headers at least 12px');
 await p.setViewportSize({width:1440,height:900});await p.evaluate(()=>scrollTo(0,0));const desktopRows=await p.locator('#leaderboard-entries tr').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().bottom<=innerHeight).length);ok(desktopRows>=5,'Desktop shows several complete rows: '+desktopRows);await p.setViewportSize({width:375,height:667});
 ok(await p.locator('#account-link').textContent()==='Iniciar sesión','Clear sign-in CTA');await p.locator('#account-link').click();await p.locator('#account-dialog').waitFor({state:'visible'});ok(await p.locator('#account-dialog').evaluate(e=>e.open),'Account CTA opens real dialog');await p.goto('http://127.0.0.1:4173/leaderboard.html?lang=en');await p.locator('#leaderboard-table').waitFor({state:'visible'});
 ok(calls.every(c=>c.body.action==='leaderboard'&&c.body.limit===20),'Only read-only leaderboard requests');
 await context.clearCookies();await p.evaluate(()=>localStorage.clear());await context.route('https://cdn.jsdelivr.net/npm/@supabase/**',r=>r.abort());await p.evaluate(()=>localStorage.setItem('derabona.auth.v1','MOCK'));await p.reload();await p.locator('#leaderboard-table').waitFor({state:'visible'});ok(!calls.at(-1).headers.authorization,'Failed SDK leaves public board usable');
 await p.evaluate(()=>localStorage.clear());await p.goto('http://127.0.0.1:4173/index.html?lang=en');await p.locator('#hint').click();const saved=await p.evaluate(()=>sessionStorage.getItem('touchline.career.v1'));await p.locator('#leaderboard-open').click();await p.locator('#leaderboard-table').waitFor({state:'visible'});ok(await p.evaluate(v=>sessionStorage.getItem('touchline.career.v1')===v,saved),'Board does not mutate gameplay save');await p.locator('#bottom-play').click();await p.locator('#hint').waitFor();ok(await p.evaluate(v=>sessionStorage.getItem('touchline.career.v1')===v,saved),'Game-board-game preserves engaged round');
 // Deterministic virtual-clock deadlines, in isolated contexts, no private cache.
 for(const mode of ['sdk','session']){
 const c=await page.context().browser().newContext({viewport:{width:375,height:667},reducedMotion:'reduce'});let sdkRelease,requests=0;
 try{
 await c.addInitScript(()=>localStorage.setItem('derabona.auth.v1','MOCK'));
 await c.route('https://cdn.jsdelivr.net/npm/@supabase/**',async r=>{if(mode==='sdk')await new Promise(resolve=>sdkRelease=resolve);await r.fulfill({contentType:'application/javascript',body:`window.supabase={createClient:()=>({auth:{getSession:()=>new Promise(resolve=>window.finishSession=resolve),onAuthStateChange:fn=>{window.authListener=fn;}}})};`}).catch(()=>{});});
 await c.route('**/functions/v1/ranked-game',r=>{if(r.request().method()==='OPTIONS')return r.fulfill({status:204,headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*'}});requests++;return r.fulfill({headers:{'access-control-allow-origin':'*'},contentType:'application/json',body:JSON.stringify({entries:[],total:0,own:null})});});
 const q=await c.newPage();await q.clock.install();await q.goto('http://127.0.0.1:4173/leaderboard.html?lang=en',{waitUntil:'domcontentloaded'});await loading(q,'Delayed '+mode);if(mode==='session')await q.waitForFunction(()=>!!window.finishSession);else while(!sdkRelease)await q.waitForTimeout(10);
 ok(requests===0,'No speculative public request during '+mode);
 ok(await q.locator('.board-spinner').evaluate(e=>getComputedStyle(e).animationName==='none'),'Reduced motion disables spinner animation '+mode);
 await q.clock.runFor(5100);await q.waitForFunction(()=>document.querySelector('#leaderboard-status').dataset.state==='empty',{},{timeout:1500});await settled(q,'Timed-out '+mode);ok(requests===1&&(await q.locator('#personal-detail').textContent()).includes('public'),'Bounded '+mode+' falls back once with truthful account warning');
 if(mode==='session'){await q.evaluate(()=>window.finishSession({data:{session:{access_token:'LATE',user:{id:'late'}}},error:null}));await q.clock.runFor(100);ok(requests===1&&await q.locator('#leaderboard-own').textContent()==='','Late session cannot restore private rank');}
 }finally{sdkRelease?.();await c.close();}
 }
 const staticContext=await page.context().browser().newContext({javaScriptEnabled:false,viewport:{width:375,height:667}});try{const q=await staticContext.newPage();await q.goto('http://127.0.0.1:4173/leaderboard.html');const note=q.locator('noscript p'),bounds=await note.boundingBox();ok(await q.locator('#board-loading').isHidden()&&await q.locator('#leaderboard-status').isHidden()&&await q.locator('#board-results').getAttribute('aria-busy')==='false'&&await note.isVisible()&&(await note.textContent()).includes('necesita JavaScript')&&bounds.y>=0&&bounds.y+bounds.height<=667,'No JavaScript shows visible explanation without endless loading or busy status');}finally{await staticContext.close();}
 const earlyContext=await page.context().browser().newContext({viewport:{width:375,height:667}});try{await earlyContext.route('**/leaderboard.html',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).split('<script id="leaderboard-app">')[0]+'</body></html>'});});const q=await earlyContext.newPage();await q.goto('http://127.0.0.1:4173/leaderboard.html');await loading(q,'Early script-enabled markup without application script');ok(await q.locator('#leaderboard-status').isVisible()&&(await q.locator('#leaderboard-status').textContent()).includes('Cargando'),'Early loading retains accessible status before application download');}finally{await earlyContext.close();}
 ok(errors.length===0,'No runtime errors');return {passed:true,backend:'EXPLICIT SDK/API ROUTE MOCKS',checks,errors};
 }catch(error){throw Error(error.message+' errors: '+errors.join(',')+' calls: '+JSON.stringify(calls.slice(-3))+' | passed: '+checks.join('; '));}finally{release?.();await context.close();}
}
